# Generated by Django 4.2.4 on 2023-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='crash_point',
            field=models.CharField(default='', max_length=255),
        ),
    ]
