# Generated by Django 4.2.4 on 2023-11-02 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersbank',
            name='total_deposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='ownersbank',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.CreateModel(
            name='UsersDepositsandWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('withdrawals', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
