# Generated by Django 4.2.4 on 2023-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='group_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
