# Generated by Django 4.2.4 on 2023-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0002_ownersbank_total_deposits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdepositsandwithdrawals',
            old_name='deposits',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='usersdepositsandwithdrawals',
            old_name='withdrawals',
            new_name='withdrawal',
        ),
        migrations.AddField(
            model_name='usersdepositsandwithdrawals',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersdepositsandwithdrawals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
