# Generated by Django 4.2.4 on 2023-11-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0005_usersdepositsandwithdrawals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
