# Generated by Django 4.2.4 on 2023-11-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0006_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
