# Generated by Django 4.2.4 on 2023-11-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0007_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
