# Generated by Django 4.2.4 on 2023-11-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0008_delete_custompermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_admin_page', 'Can view adminpage')]},
        ),
    ]
