# Generated by Django 4.2.4 on 2023-11-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_admin_page', 'Can view adminpage'), ('custom_admin_permission', 'Can access the custom admin page')]},
        ),
    ]
